10021	OUTOFSCOPE	(X-Content-Type-Options Header Missing)
10037	OUTOFSCOPE	(Server Leaks Information via X-Powered-By)
10049	OUTOFSCOPE	(Storable and Cacheable Content)
10055	OUTOFSCOPE	(CSP Directive Missing)
10063	OUTOFSCOPE	(Permissions Policy Header Not Set)
90004	OUTOFSCOPE	(Cross-Origin-Resource-Policy Header Missing)
