env:
  contexts:
    - name: "SecureShop Admin Context"
      urls:
        - "http://localhost:3000"
      includePaths:
        - "http://localhost:3000/api/.*"
      excludePaths: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true

jobs:
  - type: authentication
    parameters:
      context: "SecureShop Admin Context"
      method: "json"
      loginUrl: "http://localhost:3000/api/auth/login"
      loginRequestData: '{"email":"admin@admin.com","password":"admin1234"}'
      verificationRegex: '\Q"message":"Logged in"\E'
      sessionManagementMethod: "cookie"
      sessionManagementParameter: "token"
      username: "admin"

  - type: spider
    parameters:
      context: "SecureShop Admin Context"
      maxDuration: 5
      maxDepth: 10

  - type: passiveScan-wait
    parameters:
      maxDuration: 5

  - type: activeScan
    parameters:
      context: "SecureShop Admin Context"
      policy: "API-scan-minimal"
      maxScanDurationInMins: 10

  - type: report
    parameters:
      template: "traditional-json"
      reportDir: "/zap/wrk/zap-reports"
      reportFile: "zap-admin-report.json"
      reportTitle: "SecureShop Admin Context Scan"
