env:
  contexts:
    - name: "SecureShop User Context"
      urls:
        - "http://localhost:3000"
      includePaths:
        - "http://localhost:3000/api/.*"
      excludePaths:
        - "http://localhost:3000/api/admin/.*"
      authentication:
        method: "json"
        parameters:
          loginRequestUrl: "http://localhost:3000/api/auth/login"
          loginRequestBody: '{"email":"{%username%}","password":"{%password%"}'
        verification:
          method: "response"
          loggedInRegex: '\Q"message":"Logged in"\E'
          loggedOutRegex: '\QAuthentication required\E'
      sessionManagement:
        method: "cookie"
        parameters:
          cookieName: "token"
      users:
        - name: "test"
          credentials:
            username: "test@test.com"
            password: "test1234"
  parameters:
    failOnError: false
    failOnWarning: false
    progressToStdout: true

jobs:
  - type: spider
    parameters:
      context: "SecureShop User Context"
      user: "test"
      maxDuration: 5
      maxDepth: 10

  - type: passiveScan-wait
    parameters:
      maxDuration: 5

  - type: activeScan
    parameters:
      context: "SecureShop User Context"
      user: "test"
      maxScanDurationInMins: 10

  - type: report
    parameters:
      template: "traditional-json"
      reportDir: "/zap/wrk/zap-reports"
      reportFile: "zap-user-report.json"
      reportTitle: "SecureShop User Context Scan"
