name: Security Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: |
         semgrep scan \
          --config .semgrep \
          --sarif \
          --output semgrep.sarif \
          . || true
      
      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif
  
  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: json
          output: trivy-results.json
          exit-code: 0

      - name: Apply Trivy polices
        run : python scripts/trivy-policies.py

  container-scan:
    runs-on: ubuntu-latest
    needs: [trivy]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: build docker image
        run: docker build -t secureshop:${{github.sha}} .
      
      - name: Trivy container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secureshop:${{ github.sha }}
          scan-type: image
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
      - name: Generate SBOM 
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secureshop:${{ github.sha }}
          format: 'cyclonedx'
          output: 'secureshop-sbom.json'
      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: secureshop-sbom
          path: secureshop-sbom.json


  zap:
    runs-on: ubuntu-latest
    needs:
    - trivy

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: |
        node src/server.js &
        sleep 15

    - name: ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.12.0
      with:
        target: "http://localhost:3000"
        fail_action: true
  
  zapAuthenticated:
    runs-on: ubuntu-latest
    needs:
      - trivy
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: install dependencies:
        run: npm ci

      - name: seed database
        run: npm run seed
      
      - name: wait
        run: sleep 15
      
      - name: create report directory
        run: mkdir zap-reports
      
      - name: Zap user context scan
        run: |
          docker run --network="host" \
            -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap.sh -cmd -autorun /zap/wrk/.zap/authentication-user.yaml
        continue-on-error: true

      - name: Zap admin context scan
        run: |
          docker run --network="host" \
            -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap.sh -cmd -autorun /zap/wrk/.zap/authentication-admin.yaml
        continue-on-error: true
      
      - name: upload zap reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-
          path: zap-reports/

      - name: check ZAP Results
        run: python scripts/check-zap-results.py

  gitLeaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Run gitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

